### PR TITLE
Converted to Python3.

### PR DESCRIPTION
**Pull request by limburgher**
…is all works with Python2.

Might want to revert the INSTALL and bin/trelby shebang changes until wxPython is ready for Python3.

### CODE REVIEW

**Comment by limburgher** [comment]
https://docs.wxpython.org/MigrationGuide.html

**Comment by limburgher** [comment]
Currently everything works except the Dialogue Report and spell check.

**Comment by limburgher** [comment]
Dialogue report works but returns different results from Python2. Other than that and tests, this is ready to go.

**Comment by sTiKyt** [comment]
Cool

**Pull request closed without merging**
